### PR TITLE
RequireJS-related fixes

### PR DESCRIPTION
**Pull request by ivanobulo**
Fixed requirejs config. Added 'backpressure' and 'sorting' modules. Also added 'all', 'lite' and 'lite.extras' variations of rxjs library.

### CODE REVIEW

**Comment by jamesward** [comment]
Thanks @ivanobulo.  One thing we should fix in this change set and retroactively is that RequireJS modules are not allowed to have dots in their names.  Can you fix that in this PR?

**Comment by ivanobulo** [comment]
Done. Please take a look again.
Thanks!

**Comment by jamesward** [comment]
Thanks @ivanobulo. I think all of the shim module names also need to not have dots in them.  But I'm not exactly sure why those are even in there since there aren't path configs for any of those anyhow.  How are they used and for what?

**Comment by ivanobulo** [comment]
@jamesward From what I read shim configuration defines order in which script is loaded. Shim config names can be also used as a dependency references. I checked locally it works pretty good with dots.
Can you please give details on limitation with dots in names for RequireJS modules? Is it a limitation in the WebJars/Play codebase?

**Comment by jamesward** [comment]
If it works for you then lets go with it.

**Pull request merged**
